title: Blog Transports du Futur
description: Archives restaurées
baseurl: "/transportsdufutur"  # Le nom du dépôt GitHub (important pour les liens)
url: "https://gabrielplassat.github.io"
theme: minima
markdown: kramdown

permalink: /:year/:month/:title/

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"